### ISSUE TITLE
Special conditions & product type

### ISSUE THREAD

**Issue by seansan** [firegento/firegento-dynamiccategory#27]
Would great if we can add some "quick rules, Special conditions" like
- In Promotion
- Is New
- Created on/after date
- Quantity in stock
- In stock

Also I am missing one important one
- Product type (simple/bundled/configurable)

In addition it should maybe check for Enabled & Visibility by default?

![naamloos-1](https://cloud.githubusercontent.com/assets/652395/6471424/2abdaa34-c1eb-11e4-908a-1380cfa8d07c.png)

**Comment by seansan** [comment]
Maybe something for the next Hackathon #27 /w #28 

I can also add some more ideas for making this even better

**Comment by seansan** [comment]
I was thinking of adding some more details. 

But this is clear. +1 for this issue, because I do think it is most important for now

To elaborare a little on these two:
Quantity in stock + In stock

In stock = the configurable product itself is in stock

Quantity in stock = means that the configurable product itself is in stock + the (underlying) simple products have a QTY > 0 && are set to in stock (so products are actually available to sell)

**Comment by therouv** [comment]
@seansan 

> Also I am missing one important one: Product type (simple/bundled/configurable)

This filter is now available.

> In addition it should maybe check for Enabled & Visibility by default?

Just allow the attributes "visibility" and "status" for promo rules in *Catalog > Attributes > Manage Attributes".

**Comment by seansan** [comment]
Cool. That's true.

Related to:In addition it should maybe check for Enabled & Visibility by default?
Doesn't the category functionality show Enabled. Visible. And in stock products only. Hence the filter seems to be there already indirectly. So maybe this is a non issue. 



Great work!

**Comment by therouv** [comment]
In my opinion, only a filter like "only show products with more than 50 items in stock" would make sense. But it seems like a huge overhead to implement additional stock checks, and since category already filters non-available products, I think we can close this issue.

**Comment by seansan** [comment]
Hi rouven. What about special price/promotion. New products filter. Stock qty >. These three are important especially the first two. 

Would you open a new call for that? Or was the issue closed too soon. 

Should be able to create a category. New products. Or a category items on sale. I think this is important. 






Sent from my iPhone.

On 10 May 2015, at 10:41, Rouven Alexander Rieker <notifications@github.com> wrote:

Closed #27.
