### ISSUE TITLE
Add cron on/off + scheduling options in backend

### ISSUE THREAD

**Issue by shirtsofholl** [firegento/firegento-dynamiccategory#33]
Now that cron may be added. The next steo is to add a switch on/off for cron + add a field to enter a cron schedule manually (instead of hardcoded)

**Comment by seansan** [comment]
To elaborate, maybe add something like

![image](https://cloud.githubusercontent.com/assets/652395/6527443/0c17003a-c41b-11e4-9334-9ad1f87d15e2.png)

and setting the timing

![image](https://cloud.githubusercontent.com/assets/652395/6527450/255f2eb4-c41b-11e4-81ef-d7015b3f15e6.png)

**Comment by therouv** [comment]
I made the cron expr configurable in the backend. I didn't add an on/off switch because if you delete the value in the cron expr field, the cronjob won't be triggered.

**Comment by shirtsofholl** [comment]
nice ;P


_________________________________________________________
info@shirtsofholland.com | KvK 60827378 | http://shirtsofholland.com

[image: ShirtsofHolland - dé specialist in Oranje kleding]
<http://shirtsofholland.com/>

2015-05-09 12:50 GMT+02:00 Rouven Alexander Rieker <notifications@github.com

**Comment by shirtsofholl** [comment]
Does it have/need a default value?

Would one expect a CRON to be enabled by default or vice versa

Maybe add comment to explain empty value workings


_________________________________________________________
info@shirtsofholland.com | KvK 60827378 | http://shirtsofholland.com

[image: ShirtsofHolland - dé specialist in Oranje kleding]
<http://shirtsofholland.com/>

2015-05-09 12:50 GMT+02:00 Rouven Alexander Rieker <notifications@github.com

**Comment by therouv** [comment]
Default value is `* 2 * * *` so every morning at 2 a.m.
