### ISSUE TITLE
Add extension enabled/disabled button in backend?

### ISSUE THREAD

**Issue by seansan** [firegento/firegento-dynamiccategory#34]
Add extension enabled/disabled button in backend?

Not critcal .. because why else would you install it? But maybe handy for testing etc etc - or disable in certain storeviews

![image](https://cloud.githubusercontent.com/assets/652395/6527467/3f5d5f52-c41b-11e4-9ea9-7d41de8785a8.png)

**Comment by therouv** [comment]
@seansan I don't really see the use case for activating/deactivating this extension. 

DynamicCategory adds products based on rules to specific categories. This relationship is by default without any scope (see table `catalog_category_product`). The scope (in this case via store_id) is added only during the indexing.

**Comment by seansan** [comment]
I was thinking more along the lines of - when one has a problem with the
extension

But I agree that when the dynamic behavior becomes so default - that one
can have it "always on" - but dont configure any dynamic categories

I am maybe just accustomed to being able to enable/disable extensions ...

**Comment by therouv** [comment]
Disabling a module should be done via `app/etc/modules/FireGento_DynamicCategory.xml` as in only this setting disables the module completely.
