### ISSUE TITLE
Reindex dynamiccategory error

### ISSUE THREAD

**Issue by webmastermicromaint** [firegento/firegento-dynamiccategory#52]
When I try to do the reindex of dynamiccategory, it gives me the following error:
"PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 632 bytes) in /dati/maintstore/htdocs/golive.micromaint.com/lib/Zend/Db/Statement/Pdo.php on line 228"

- memory limit is set on 512M
- 2300 Products
- 630 Categories

Is it normal that with 512M give me this error ?
Are there any solutions ?

Thanks

**Comment by Schrank** [comment]
As you can see in the error your memory size is * 134217728 bytes* which is 128MB. This might be changed by .htaccess or ini_set somewhere. Try to change this. If it doesn't help, please reopen.

**Comment by webmastermicromaint** [comment]
I set memory limit 256M now Reindex dynamiccategory works fine.

This reindex takes around 6-7 minutes.
Is it normal that this reindex takes so much time and memory? 
Are there others ways or any optimizations that i can do? 

Thanks so much.

**Comment by webmastermicromaint** [comment]
I set memory limit 256M now Reindex dynamiccategory works fine.

This reindex takes around 6-7 minutes.
Is it normal that this reindex takes so much time and memory? 
Are there others ways or any optimizations that i can do?

Thanks so much.


-----Messaggio originale-----
Da: Fabian Blechschmidt [mailto:notifications@github.com]
Inviato: venerdì 18 settembre 2015 9.11
A: firegento/firegento-dynamiccategory
Cc: webmastermicromaint
Oggetto: Re: [firegento-dynamiccategory] Reindex dynamiccategory error (#52)


As you can see in the error your memory size is * 134217728 bytes* which is 128MB. This might be changed by .htaccess or ini_set somewhere. Try to change this. If it doesn't help, please reopen.
