### ISSUE TITLE
Cron expression for 2 a.m. is "0 2 * * *"

### ISSUE THREAD

**Issue by mrrdbl83** [firegento/firegento-dynamiccategory#57]
Hello, your extension is very neat. Just a small hint: 
"* 2 * * *" is not a cron expression for 2 a.m., but for "every minute in the second hour of each day".
"0 2 * * *" would be 2 a.m.

It's a small but important change, because it can slow down the server, if the job is started 2:00, 2:01, 2:02 and so on. ;-)

**Comment by therouv** [comment]
Hi @mrrdbl83 Good catch, thank you. Fixed in new release 1.2.2.
